class Metrics:
    """
    Class holding metrics options for the UI.
    """

    Spot = [
        "Time point",
        "X coordinate",
        "Y coordinate",
        "Distance",
        "Direction"
        "Cumulative length",
        "Cumulative displacement",
        "Cumulative confinement ratio",
    ]

    Track = [
        "Track length",
        "Track displacement",
        "Confinement ratio",
        "Track points",
        "Speed mean",
        "Speed median",
        "Speed max",
        "Speed min",
        "Speed std",
        "Direction mean",
        "Direction std",
    ]

    Time = [
        "Track length",
        "Track displacement",
        "Confinement ratio",
        "Speed"
    ]

    LookFor = {
        "select_id": ["track id", "track identifier", "track"],
        "select_t": ["position t", "t position", "time", "time position", "frame", "t"],
        "select_x": ["position x", "x position", "x coordinate", "coordinate x", "x",],
        "select_y": ["position y", "y position", "y coordinate", "coordinate y", "y"],
    }

    Lut = [
        "Track length", 
        "Track displacement", 
        "Confinement ratio",
        "Track points",
        "Speed instantaneous",
        "Speed mean",
        "Speed median",
        "Speed max",
        "Speed min",
        "Speed std",
        "Direction mean",
        "Direction sd",
    ]

    class Units:
        """
        Class holding units options for the UI.
        """

        TimeUnits = {
            "seconds": "s",
            "minutes": "min",
            "hours": "h",
            "days": "d",
        }

        @staticmethod
        def SetUnits(t: str) -> dict:
            return {
                "Track length": "(µm)",
                "Track displacement": "(µm)",
                "Confinement ratio": "",
                "Track points": "",
                "Time point": f"({t})",
                "X coordinate": "(µm)",
                "Y coordinate": "(µm)",
                "Speed mean": f"(µm·{t}⁻¹)",
                "Speed median": f"(µm·{t}⁻¹)",
                "Speed max": f"(µm·{t}⁻¹)",
                "Speed min": f"(µm·{t}⁻¹)",
                "Speed std": f"(µm·{t}⁻¹)",
                "Speed instantaneous": f"(µm·{t}⁻¹)",
                "Direction mean": "",
                "Direction sd": "",
            }
    

    class Thresholding:

        SpotProperties = [
            "Time point",
            "X coordinate",
            "Y coordinate",
        ]

        TrackProperties = [
            "Track length",
            "Track displacement",
            "Confinement ratio",
            "Track points",
            "Speed mean",
            "Speed std",
            "Direction mean",
        ]

        Properties = TrackProperties + SpotProperties




class Styles:
    """
    Class holding color options for the UI.
    """

    ColorMode = [
        "single color",
        "random colors",
        "random greys",
        "differentiate conditions",
        "differentiate replicates",
        "greyscale LUT",
        "reverse grayscale LUT",
        "jet LUT",
        "brg LUT",
        "cool LUT",
        "hot LUT",
        "inferno LUT",
        "plasma LUT",
        "CMR-map LUT",
        "gist-stern LUT",
        "gnuplot LUT",
        "viridis LUT",
        "cividis LUT",
        "rainbow LUT",
        "turbo LUT",
        "nipy-spectral LUT",
        "gist-ncar LUT",
        "twilight LUT",
        "seismic LUT",
    ]

    LUTOptions = [
        "greyscale LUT",
        "reverse grayscale LUT",
        "jet LUT",
        "brg LUT",
        "cool LUT",
        "hot LUT",
        "inferno LUT",
        "plasma LUT",
        "CMR-map LUT",
        "gist-stern LUT",
        "gnuplot LUT",
        "viridis LUT",
        "cividis LUT",
        "rainbow LUT",
        "turbo LUT",
        "nipy-spectral LUT",
        "gist-ncar LUT",
        "twilight LUT",
        "seismic LUT",
    ]

    PaletteQualitativeMatplotlib = [
        "Set1",
        "Set2",
        "Set3",
        "tab10",
        "Accent",
        "Dark2",
        "Pastel1",
        "Pastel2"
    ]

    PaletteQualitativeSeaborn = [
        "deep", 
        "muted", 
        "bright", 
        "pastel", 
        "dark", 
        "colorblind", 
        "husl",
        "hsl"
    ]

    PaletteQualitativeAltair = [
        "category10",
        "tableau10",
        "observable10",
        "set1",
        "set2",
        "set3",
        "pastel1",
        "pastel2",
        "dark2",
        "accent"
    ]

    # ...existing code...
    PaletteQualitativeAltair = [
        "category10",
        "tableau10",
        "observable10",
        "set1",
        "set2",
        "set3",
        "pastel1",
        "pastel2",
        "dark2",
        "accent"
    ]

    Color = {
        "black": "#000000",
        "onyx": "#0f0f0f",
        "deep ocean": "#070d0d",
        "space": "#1a1a1a",
        "charcoal": "#343837",
        "charcoal grey": "#3c4142",
        "dark grey": "#363737",
        "dim grey": "#4a4e4d",
        "gunmetal": "#536267",
        "slate grey": "#59656d",
        "slate": "#516572",
        "grey": "#929591",
        "steel": "#738595",
        "medium grey": "#7d7f7c",
        "cool grey": "#95a3a6",
        "silver": "#c5c9c7",
        "light grey": "#d8dcd6",
        "off white": "#ffffe4",
        "white": "#ffffff",
        "mahogany": "#4a0100",
        "blood": "#770001",
        "dark red": "#840000",
        "maroon": "#650021",
        "burgundy": "#610023",
        "claret": "#680018",
        "wine": "#80013f",
        "wine red": "#7b0323",
        "red wine": "#8c0034",
        "bordeaux": "#7b002c",
        "blood red": "#980002",
        "deep red": "#9a0200",
        "darkish red": "#a90308",
        "crimson": "#8c000f",
        "rusty red": "#af2f0d",
        "brick red": "#8f1402",
        "burnt red": "#9f2305",
        "red brown": "#8b2e16",
        "rust": "#a83c09",
        "brick": "#a03623",
        "fire engine red": "#fe0002",
        "red": "#e50000",
        "bright red": "#ff000d",
        "cherry red": "#f7022a",
        "cherry": "#cf0234",
        "scarlet": "#be0119",
        "vermillion": "#f4320c",
        "tomato red": "#ec2d01",
        "tomato": "#ef4026",
        "orangey red": "#fa4224",
        "red orange": "#fd3c06",
        "neon red": "#ff073a",
        "strawberry": "#fb2943",
        "light red": "#ff474c",
        "pale red": "#d9544d",
        "lightish red": "#fe2f4a",
        "pinkish red": "#f10c45",
        "rose red": "#be013c",
        "indian red": "#850e04",
        "carmine": "#9d0216",
        "chocolate": "#3d1c02",
        "chocolate brown": "#411900",
        "dark brown": "#341c02",
        "very dark brown": "#1d0200",
        "sepia": "#985e2b",
        "coffee": "#a6814c",
        "brown": "#653700",
        "saddle brown": "#583101",
        "russet": "#a13905",
        "sienna": "#a9561e",
        "burnt sienna": "#b04e0f",
        "burnt umber": "#a0450e",
        "umber": "#b26400",
        "rust orange": "#c45508",
        "burnt orange": "#c04e01",
        "pumpkin": "#e17701",
        "pumpkin orange": "#fb7d07",
        "orange brown": "#be6400",
        "brown orange": "#b96902",
        "ochre": "#bf9005",
        "dark orange": "#c65102",
        "orange": "#f97306",
        "bright orange": "#ff5b00",
        "blood orange": "#fe4b03",
        "orangered": "#fe420f",
        "reddish orange": "#f8481c",
        "tangerine": "#ff9408",
        "mandarin": "#f9bc08",
        "light orange": "#fdaa48",
        "peach": "#ffb07c",
        "apricot": "#ffb16d",
        "melon": "#ff7855",
        "salmon": "#ff796c",
        "salmon pink": "#fe7b7c",
        "coral": "#fc5a50",
        "coral pink": "#ff6163",
        "pastel orange": "#ff964f",
        "faded orange": "#f0944d",
        "terra cotta": "#c9643b",
        "terracotta": "#ca6641",
        "clay": "#b66a50",
        "clay brown": "#b2713d",
        "copper": "#b66325",
        "bronze": "#a87900",
        "caramel": "#af6f09",
        "butterscotch": "#fdb147",
        "tan": "#d1b26f",
        "sand": "#e2ca76",
        "sandstone": "#c9ae74",
        "beige": "#e6daa6",
        "buff": "#fef69e",
        "wheat": "#fbdd7e",
        "khaki": "#aaa662",
        "camel": "#c69f59",
        "fawn": "#cfaf7b",
        "taupe": "#b9a281",
        "dark beige": "#ac9362",
        "dirt": "#8a6e45",
        "dirt brown": "#836539",
        "mud": "#735c12",
        "mud brown": "#60460f",
        "golden rod": "#f9bc08",
        "goldenrod": "#fac205",
        "gold": "#dbb40c",
        "dark gold": "#b59410",
        "mustard": "#ceb301",
        "mustard yellow": "#d2bd0a",
        "dark yellow": "#d5b60a",
        "yellow brown": "#b79400",
        "yellow ochre": "#cb9d06",
        "olive yellow": "#c2b709",
        "brass": "#b5a642",
        "yellow": "#ffff14",
        "canary": "#fdff63",
        "canary yellow": "#fffe40",
        "lemon": "#fdff52",
        "lemon yellow": "#fdff38",
        "bright yellow": "#fffd01",
        "sunflower": "#ffc512",
        "sunflower yellow": "#ffda03",
        "sun yellow": "#ffdf22",
        "sunny yellow": "#fff917",
        "sunshine yellow": "#fffd37",
        "banana": "#ffff7e",
        "banana yellow": "#fafe4b",
        "butter": "#ffff81",
        "butter yellow": "#fffd74",
        "cream": "#ffffc2",
        "pale yellow": "#ffff84",
        "light yellow": "#fffe7a",
        "pastel yellow": "#fffe71",
        "ivory": "#ffffcb",
        "eggshell": "#ffffd4",
        "olive": "#6e750e",
        "dark olive": "#373e02",
        "olive drab": "#6f7632",
        "olive green": "#677a04",
        "army green": "#4b5d16",
        "military green": "#667c3e",
        "swamp": "#698339",
        "swamp green": "#748500",
        "camo": "#7f8f4e",
        "camo green": "#526525",
        "camouflage green": "#4b6113",
        "drab": "#828344",
        "drab green": "#749551",
        "stone": "#ada587",
        "moss": "#769958",
        "moss green": "#658b38",
        "dark olive green": "#3c4d03",
        "forest": "#0b5509",
        "forest green": "#06470c",
        "dark forest green": "#002d04",
        "dark green": "#033500",
        "hunter green": "#0b4008",
        "bottle green": "#044a05",
        "evergreen": "#05472a",
        "pine": "#2b5d34",
        "pine green": "#0a481e",
        "racing green": "#014600",
        "british racing green": "#05480d",
        "jungle green": "#048243",
        "emerald": "#01a049",
        "emerald green": "#028f1e",
        "shamrock": "#01b44c",
        "shamrock green": "#02c14d",
        "green": "#15b01a",
        "true green": "#089404",
        "grass": "#5cac2d",
        "grass green": "#3f9b0b",
        "lawn green": "#4da409",
        "dark grass green": "#388004",
        "fern": "#63a950",
        "fern green": "#548d44",
        "leaf": "#71aa34",
        "leaf green": "#5ca904",
        "leafy green": "#51b73b",
        "tree green": "#2a7e19",
        "bright green": "#01ff07",
        "vivid green": "#2fef10",
        "electric green": "#21fc0d",
        "neon green": "#0cff0c",
        "fluorescent green": "#08ff08",
        "hot green": "#25ff29",
        "lime": "#aaff32",
        "lime green": "#89fe05",
        "bright lime": "#87fd05",
        "bright lime green": "#65fe08",
        "acid green": "#8ffe09",
        "chartreuse": "#c1f80a",
        "yellow green": "#c0fb2d",
        "yellowgreen": "#bbf90f",
        "green yellow": "#c9ff27",
        "apple": "#6ecb3c",
        "apple green": "#76cd26",
        "green apple": "#5edc1f",
        "kelly green": "#02ab2e",
        "irish green": "#019529",
        "frog green": "#58bc08",
        "dark lime": "#84b701",
        "dark lime green": "#7ebd01",
        "pea": "#a4bf20",
        "pea green": "#8eab12",
        "pea soup": "#929901",
        "pea soup green": "#94a617",
        "avocado": "#90b134",
        "avocado green": "#87a922",
        "asparagus": "#77ab56",
        "sage": "#87ae73",
        "sage green": "#88b378",
        "grey green": "#789b73",
        "light green": "#96f97b",
        "pale green": "#c7fdb5",
        "pastel green": "#b0ff9d",
        "mint": "#9ffeb0",
        "mint green": "#8fff9f",
        "light mint": "#b6ffbb",
        "light mint green": "#a6fbb2",
        "spearmint": "#1ef876",
        "seafoam": "#80f9ad",
        "seafoam green": "#7af9ab",
        "light seafoam": "#a0febf",
        "light seafoam green": "#a7ffb5",
        "foam green": "#90fda9",
        "spring green": "#a9f971",
        "celery": "#c1fd95",
        "celadon": "#befdb7",
        "very light green": "#d1ffbd",
        "very pale green": "#cffdbc",
        "teal": "#029386",
        "dark teal": "#014d4e",
        "deep teal": "#00555a",
        "teal green": "#25a36f",
        "teal blue": "#01889f",
        "green blue": "#06b48b",
        "blue green": "#137e6d",
        "dark blue green": "#005249",
        "sea green": "#53fca1",
        "dark sea green": "#11875d",
        "light sea green": "#98f6b0",
        "ocean green": "#3d9973",
        "viridian": "#1e9167",
        "jade": "#1fa774",
        "jade green": "#2baf6a",
        "turquoise": "#06c2ac",
        "dark turquoise": "#045c5a",
        "bright turquoise": "#0ffef9",
        "turquoise green": "#04f489",
        "turquoise blue": "#06b1c4",
        "aqua": "#13eac9",
        "dark aqua": "#05696b",
        "deep aqua": "#08787f",
        "bright aqua": "#0bf9ea",
        "light aqua": "#8cffdb",
        "aquamarine": "#04d8b2",
        "light aquamarine": "#7bfdc7",
        "dark aquamarine": "#017371",
        "cyan": "#00ffff",
        "bright cyan": "#41fdfe",
        "light cyan": "#acfffc",
        "pale cyan": "#b7fffa",
        "robin's egg": "#6dedfd",
        "robin's egg blue": "#98eff9",
        "robin egg blue": "#8af1fe",
        "tiffany blue": "#7bf2da",
        "ice": "#d6fffa",
        "ice blue": "#d7fffe",
        "navy": "#01153e",
        "navy blue": "#001146",
        "dark navy": "#000435",
        "dark navy blue": "#00022e",
        "very dark blue": "#000133",
        "midnight": "#03012d",
        "midnight blue": "#020035",
        "dark blue": "#00035b",
        "deep blue": "#040273",
        "royal blue": "#0504aa",
        "dark royal blue": "#02066f",
        "royal": "#0c1793",
        "dark steel blue": "#1b2431",
        "cobalt": "#1e488f",
        "cobalt blue": "#030aa7",
        "prussian blue": "#004577",
        "marine": "#042e60",
        "marine blue": "#01386a",
        "ocean": "#017b92",
        "ocean blue": "#03719c",
        "deep sea blue": "#015482",
        "sapphire": "#2138ab",
        "blue": "#0343df",
        "pure blue": "#0203e2",
        "true blue": "#010fcc",
        "vivid blue": "#152eff",
        "bright blue": "#0165fc",
        "electric blue": "#0652ff",
        "neon blue": "#04d9ff",
        "strong blue": "#0c06f7",
        "primary blue": "#0804f9",
        "rich blue": "#021bf9",
        "clear blue": "#247afd",
        "vibrant blue": "#0339f8",
        "azure": "#069af3",
        "cerulean": "#0485d1",
        "cerulean blue": "#056eee",
        "sky blue": "#75bbfd",
        "bright sky blue": "#02ccfe",
        "deep sky blue": "#0d75f8",
        "dark sky blue": "#448ee4",
        "light sky blue": "#c6fcff",
        "pale sky blue": "#bdf6fe",
        "light blue": "#95d0fc",
        "baby blue": "#a2cffe",
        "powder blue": "#b1d1fc",
        "pale blue": "#d0fefe",
        "very light blue": "#d5ffff",
        "periwinkle": "#8e82fe",
        "periwinkle blue": "#8f99fb",
        "light periwinkle": "#c1c6fc",
        "cornflower": "#6a79f7",
        "cornflower blue": "#5170d7",
        "denim": "#3b638c",
        "denim blue": "#3b5b92",
        "steel blue": "#5a7d9a",
        "cadet blue": "#4e7496",
        "blue grey": "#607c8e",
        "grey blue": "#6b8ba4",
        "slate blue": "#5b7c99",
        "dark slate blue": "#214761",
        "twilight": "#4e518b",
        "twilight blue": "#0a437a",
        "blueberry": "#464196",
        "indigo": "#380282",
        "dark indigo": "#1f0954",
        "indigo blue": "#3a18b1",
        "purple": "#7e1e9c",
        "dark purple": "#35063e",
        "deep purple": "#36013f",
        "midnight purple": "#280137",
        "royal purple": "#4b006e",
        "plum": "#580f41",
        "plum purple": "#4e0550",
        "dark plum": "#3f012c",
        "eggplant": "#380835",
        "aubergine": "#3d0734",
        "grape": "#6c3461",
        "grape purple": "#5d1451",
        "violet": "#9a0eea",
        "dark violet": "#34013f",
        "deep violet": "#490648",
        "blue violet": "#5d06e9",
        "violet blue": "#510ac9",
        "purple blue": "#632de9",
        "blue purple": "#5729ce",
        "blurple": "#5539cc",
        "burple": "#6832e3",
        "electric purple": "#aa23ff",
        "neon purple": "#bc13fe",
        "bright violet": "#ad0afd",
        "vivid purple": "#9900fa",
        "bright purple": "#be03fd",
        "hot purple": "#cb00f5",
        "magenta": "#c20078",
        "dark magenta": "#960056",
        "deep magenta": "#a0025c",
        "bright magenta": "#ff08e8",
        "hot magenta": "#f504c9",
        "orchid": "#c875c4",
        "medium purple": "#9e43a2",
        "amethyst": "#9b5fc0",
        "wisteria": "#a87dc2",
        "lilac": "#cea2fd",
        "pale lilac": "#e4cbff",
        "light lilac": "#edc8ff",
        "bright lilac": "#c95efb",
        "lavender": "#c79fef",
        "pale lavender": "#eecffe",
        "light lavender": "#dfc5fe",
        "lavender blue": "#8b88f8",
        "light purple": "#bf77f6",
        "pale purple": "#b790d4",
        "mauve": "#ae7181",
        "pale mauve": "#fed0fc",
        "light mauve": "#c292a1",
        "dark mauve": "#874c62",
        "puce": "#a57e52",
        "heather": "#a484ac",
        "thistle": "#d8bfd8",
        "pink": "#ff81c0",
        "light pink": "#ffd1df",
        "pale pink": "#ffcfdc",
        "baby pink": "#ffb7ce",
        "pastel pink": "#ffbacd",
        "soft pink": "#fdb0c0",
        "rose": "#cf6275",
        "rose pink": "#f7879a",
        "pale rose": "#fdc1c5",
        "light rose": "#ffc5cb",
        "dusty rose": "#c0737a",
        "old rose": "#c87f89",
        "old pink": "#c77986",
        "dark pink": "#cb416b",
        "deep pink": "#cb0162",
        "hot pink": "#ff028d",
        "neon pink": "#fe019a",
        "shocking pink": "#fe02a2",
        "bright pink": "#fe01b1",
        "electric pink": "#ff0490",
        "fuchsia": "#ed0dd9",
        "dark fuchsia": "#9d0759",
        "cerise": "#de0c62",
        "raspberry": "#b00149",
        "berry": "#990f4b",
        "mulberry": "#920a4e",
        "blush": "#f29e8e",
        "blush pink": "#fe828c",
        "carnation": "#fd798f",
        "carnation pink": "#ff7fa7",
        "bubblegum": "#ff6cb5",
        "bubblegum pink": "#fe83cc",
        "barbie pink": "#fe46a5",
        "candy pink": "#ff63e9",
        "pig pink": "#e78ea5",
        "flamingo": "#f255db",
        "violet pink": "#fb5ffc",
        "violet red": "#a50055",
        "red violet": "#9e0168",
        "purple pink": "#e03fd8",
        "pink purple": "#db4bda"
    }

    # Color = [
    #     "red",
    #     "darkred",
    #     "firebrick",
    #     "crimson",
    #     "indianred",
    #     "salmon",
    #     "lightsalmon",
    #     "tomato",
    #     "coral",
    #     "orange",
    #     "darkorange",
    #     "gold",
    #     "khaki",
    #     "lemonchiffon",
    #     "peachpuff",
    #     "wheat",
    #     "tan",
    #     "peru",
    #     "chocolate",
    #     "sienna",
    #     "brown",
    #     "maroon",
    #     "yellow",
    #     "yellowgreen",
    #     "lawngreen",
    #     "greenyellow",
    #     "springgreen",
    #     "lightgreen",
    #     "palegreen",
    #     "mediumspringgreen",
    #     "mediumseagreen",
    #     "seagreen",
    #     "forestgreen",
    #     "green",
    #     "darkgreen",
    #     "olive",
    #     "teal",
    #     "turquoise",
    #     "mediumturquoise",
    #     "paleturquoise",
    #     "cyan",
    #     "darkcyan",
    #     "aqua",
    #     "deepskyblue",
    #     "skyblue",
    #     "lightblue",
    #     "powderblue",
    #     "steelblue",
    #     "dodgerblue",
    #     "blue",
    #     "mediumblue",
    #     "darkblue",
    #     "navy",
    #     "royalblue",
    #     "slateblue",
    #     "mediumslateblue",
    #     "slategrey",
    #     "mediumorchid",
    #     "mediumpurple",
    #     "purple",
    #     "indigo",
    #     "darkviolet",
    #     "violet",
    #     "orchid",
    #     "plum",
    #     "magenta",
    #     "pink",
    #     "lightcoral",
    #     "rosybrown",
    #     "mistyrose",
    #     "lavender",
    #     "linen",
    #     "white",
    #     "snow",
    #     "whitesmoke",
    #     "lightgrey",
    #     "silver",
    #     "grey",
    #     "darkgrey",
    #     "dimgray",
    #     "black",
    # ]

    Background = [
        "white",
        "light",
        "mid",
        "dark",
        "black"
    ]

    LineStyle = [
        "solid",
        "dashed",
        "dotted",
        "dashdot",
    ]



class Markers:
    """
    Class holding marker options for the UI.
    """

    TrackHeads = {  # TODO - add smiley face markers which will enable a lut map assigning sad faces to "dead cells", so the value spectrum for the lut map will be something like track length or diffusion coefficient [0, max value in the dataset]
        "circle-full": {"symbol": "o", "fill": True},
        "circle-empty": {"symbol": "o", "fill": False},
        "diamond-full": {"symbol": "D", "fill": True},
        "diamond-empty": {"symbol": "D", "fill": False},
        "pentagon-full": {"symbol": "P", "fill": True},
        "pentagon-empty": {"symbol": "P", "fill": False},
        "hexagon-full": {"symbol": "h", "fill": True},
        "hexagon-empty": {"symbol": "h", "fill": False},
        "octagon-full": {"symbol": "p", "fill": True},
        "octagon-empty": {"symbol": "p", "fill": False},
        "star-full": {"symbol": "*", "fill": True},
        "star-empty": {"symbol": "*", "fill": False},
    }

    PlotlyOpen = [
        "circle-open", 
        "square-open", 
        "triangle-open", 
        "star-open", 
        "diamond-open", 
        "pentagon-open",
    ]

    Emoji = [
        "cell",
        "scaled",
        "trains",
        "random",
        "farm",
        "safari",
        "insects",
        "birds",
        "forest",
        "aquarium",
    ]





class Modes:
    """
    Class holding modes for various functions for the UI.
    """

    Thresholding = [
        "Literal",
        "Normalized 0-1",
        "Quantile",
        "Relative to..."
    ]

    FitModel = {
        "Linear":         "(lambda x, a, b: a * x + b, [1, 0])",
        "Quadratic":       "(lambda x, a, b, c: a * x**2 + b * x + c, [1, 1, 0])",
        "Cubic":           "(lambda x, a, b, c, d: a * x**3 + b * x**2 + c * x + d, [1, 1, 1, 0])",
        "Logarithmic":     "(lambda x, a, b: a * np.log(x + 1e-9) + b, [1, 0])",
        "Exponential":     "(lambda x, a, b, c: a * np.exp(b * x) + c, [1, 0.1, 0])",
        "Logistic Growth": "(lambda x, L, k, x0: L / (1 + np.exp(-k * (x - x0))), [max(y), 1, np.median(x)]),",
        "Sine Wave":       "(lambda x, A, w, p, c: A * np.sin(w * x + p) + c, [np.std(y), 1, 0, np.mean(y)]),",
        "Gompertz":        "(lambda x, a, b, c: a * np.exp(-b * np.exp(-c * x)), [max(y), 1, 0.1]),",
        "Power Law":       "(lambda x, a, b: a * np.power(x + 1e-9, b), [1, 1])",
    }
    
    Interpolate = [
        "none",
        "basis",
        "basis-open",
        "basis-closed",
        "bundle",
        "cardinal",
        "cardinal-open",
        "cardinal-closed",
        "catmull-rom",
        "linear",
        "linear-closed",
        "monotone",
        "natural",
        "step",
        "step-before",
        "step-after",
    ]
    
    ExtentError = [
        "std", 
        "min-max",
    ]