class PackageWarning(Warning): ...
class LabelWarning(PackageWarning): ...
class DataFrameWarning(PackageWarning): ...
class TimePointWarning(DataFrameWarning): ...
class FailedWarning(PackageWarning): ...