class PackageError(Exception): ...
class FileFormatError(PackageError): ...
class DataFrameError(PackageError): ...
class FilteringError(PackageError): ...

class ColumnsNotFoundError(DataFrameError): ...
class TimePointError(DataFrameError): ...
class DataQualityError(DataFrameError): ...