class PackageError(Exception): ...
class FileFormatError(ValueError): ...
class FileFinderError(ValueError): ...

class DataFrameError(PackageError): ...
class DataError(PackageError): ...
class FilteringError(PackageError): ...
class PainterError(PackageError): ...
class PlottingError(PackageError): ...


class ColumnsNotFoundError(DataFrameError): ...
class TimePointError(DataFrameError): ...
class DataQualityError(DataFrameError): ...

class PaletteBuilderError(PainterError): ...
class ColorGeneratorError(PainterError): ...

class MissingDataError(PlottingError): ...

class LUTError(DataError): ...

class InvalidColorRangeError(ValueError): ...

class InvalidParameterValueError(ValueError): ...

class CategorizerError(ValueError): ...

class InputError(PackageError): ...
