class PackageWarning(Warning): ...
class LabelWarning(PackageWarning): ...
class DataFrameWarning(PackageWarning): ...
class FailedWarning(PackageWarning): ...
class CategorizerWarning(PackageWarning): ...

class TimePointWarning(DataFrameWarning): ...

class PainterWarning(PackageWarning): ...
class ColorGeneratorWarning(PackageWarning): ...
class PaletteBuilderWarning(PainterWarning): ...